#!/bin/sh

#
# Make a certificate/private key pair using a locally generated
# root certificate.
#

if test $# -ne 1; then
    echo "usage: build-key <name>";
    exit 1
fi

if test $KEY_DIR; then
    cd $KEY_DIR && \
    openssl genpkey -algorithm dstu4145le -out $1.key && \
    openssl req -days 3650 -nodes -new -key $1.key -out $1.csr -config $KEY_CONFIG && \
    openssl ca -days 3650 -md dstu34311 -out $1.crt -in $1.csr -config $KEY_CONFIG && \
    chmod 0600 $1.key
else
    echo you must define KEY_DIR
fi
